name: Hexo Blog CI

on: 
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-22.04 
        
    steps:
    # 使用稳定的 actions/checkout 版本
    - name: Checkout Repository master branch
      uses: actions/checkout@v3
      
    # 使用稳定的 actions/setup-node 版本
    - name: Setup Node.js 12.x 
      uses: actions/setup-node@v3
      with:
        node-version: "16"
    
    # 安装 Hexo 及其依赖
    - name: Setup Hexo Dependencies
      run: |
        npm install hexo-cli -g
        npm install        
    
    # 配置 SSH 部署私钥
    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    # 强制将 git remote URL 切换为 SSH 格式
    - name: Force use SSH for git remote
      run: |
        git remote set-url origin git@github.com:senchin0/senchin0.github.io.git
                
    # 设置 Git 信息
    - name: Setup Git Information
      run: | 
        git config --global user.name 'senchin0' 
        git config --global user.email 'jianhua1901@outlook.com'
    
    # 部署 Hexo 网站
    - name: Deploy Hexo 
      run: |
        hexo clean
        hexo generate
        hexo deploy